### ISSUE TITLE
Where is the Source Code?

### ISSUE THREAD

**Issue by aellul27** [VoidXWalker/Atum#9]
Why are you not showing source code of a fork of an **open source mod?**

**Comment by tildejustin** [comment]
MIT doesn't require distribution of source in derivative works, unfortunately. I wish this mod was open source too.

**Comment by tildejustin** [comment]
Duncan's mod is licensed under MIT btw

**Comment by VoidXWalker** [comment]
With the source code public, this mod could be easily turned into a seed injector with just a few modifications. This is why I, together with the Minecraft speedrunning moderation team, decided to keep the source code private. If you want to see the source code for a good reason, like compatibility with a mod you are making, feel free to open a ticket in the Minecraft Java Edition Speedrunning Discord.

**Comment by aellul27** [comment]
OK, it makes sense. Anybody could take the same code and use it to fake a speedrun. Thank you for clarifying.

**Comment by ItsProfessional** [comment]
> With the source code public, this mod could be easily turned into a seed injector with just a few modifications. This is why I, together with the Minecraft speedrunning moderation team, decided to keep the source code private. If you want to see the source code for a good reason, like compatibility with a mod you are making, feel free to open a ticket in the Minecraft Java Edition Speedrunning Discord.

Java is a very easy language to decompile. Someone just needs winrar and cfr to decompile your mod and edit the source, and recompile it.

Making the mod closed source doesn't help in avoiding this.
